# Generated by Django 3.2.4 on 2021-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
